-- CONFIG --

-- Blacklisted ped models
pedblacklist = {
	"s_m_m_security_01",
	"S_M_M_MovAlien_01",
	"s_m_m_movalien_01",
	"s_m_m_movallien_01",
	"u_m_y_babyd",
	"CS_Orleans",
	"A_M_Y_ACult_01",
	 "s_m_y_clown_01",
	 "stt_prop_stunt_domino",
"sttt_prop_stunt_jump15",
"stt_prop_stunt_jump30",
"stt_prop_stunt_jump45",
			 "S_M_Y_Mime",
			 "s_f_y_stripper_01",
			 "s_m_y_cop_01",
			 "MP_F_Cop_01",
			 "S_M_Y_Sheriff_01",
			 "S_F_Y_Sheriff_01",
			 "S_M_Y_Swat_01",
			 "S_M_M_Armoured_01",
			 "S_F_Y_Ranger_01",
			 "S_M_Y_Ranger_01",
			 "U_M_Y_RSRanger_01",
			 "G_M_Y_DesArmy_01",
			 "G_M_Y_DesArmy_02",
			 "G_M_Y_DesArmy_03",
			 "G_M_Y_DesArmy_04",
			 "G_M_Y_DesArmy_05",
			 "S_M_Y_Marine_01",
			 "S_M_Y_Marine_02",
			 "S_M_Y_Marine_03",
			 "S_M_M_Marine_01", 
			 "S_M_M_Marine_02",
			 "S_M_Y_BlackOps_01",
			 "S_M_Y_BlackOps_02",
			 "S_M_Y_BlackOps_03",
			 "S_M_M_PrisGuard_01",
			 "S_M_M_Paramedic_01", 
			 "G_F_Y_Vagos_01",
			 "IG_Ramp_Gang",
			 "CSB_Ramp_gang",
			 "MP_M_FamDD_01",
			 "G_M_Y_FamDNF_01",
			 "G_M_Y_FamCA_01",
			 "G_M_Y_BallaEast_01",
			 "G_M_Y_BallaSout_01",
			 "IG_BallasOG",
			 "IG_BallasOG",
			 "G_F_Y_Ballas_01",
			 "G_M_Y_BallaOrig_01",
			 "U_F_Y_JewelAss_01",
			 "U_M_M_JewelThief",
			 "S_M_Y_PrisMuscl_01", 
			 "S_M_Y_Prisoner_01",
			 "U_M_Y_Prisoner_01",
			 "A_M_Y_MusclBeac_01",
			 "A_M_Y_MusclBeac_02",
			 "A_M_Y_Surfer_01",
			 "IG_TylerDix",
			 "u_m_y_babyd", 
			 "CS_MaryAnn",
			 "A_F_M_Beach_01",
			 "A_F_Y_Beach_01",
			 "A_F_M_FatCult_01",
			 "A_F_Y_BevHills_01",
			 "A_F_Y_BevHills_02",
			 "A_F_Y_BevHills_03",
			 "A_F_Y_BevHills_04",
			 "CSB_Bride",
			 "U_F_Y_PoppyMich",
			 "A_F_Y_SouCent_01",
			 "CSB_Anita",
			 "A_F_Y_Skater_01",
			 "U_M_O_TapHillBilly",
			 "S_M_Y_Barman_01",
			 "A_M_Y_BreakDance_01",
			 "U_M_Y_Chip",
			 "U_M_Y_GunV_01",
			 "CSB_Groom",
			 "A_M_Y_Business_02",
			 "G_M_M_ChiBoss_01",
			 "G_M_M_ChiGoon_01",
			 "G_M_M_ChiGoon_02",
			 "CSB_Hao",
			 "A_F_Y_Vinewood_03", 
			 "A_M_Y_KTown_01",
			 "A_M_Y_KTown_02",
			 "G_M_M_KorBoss_01",
			 "G_M_Y_Korean_01",
			 "G_M_Y_Korean_02",
			 "S_F_Y_MovPrem_01",
			 "A_F_M_KTown_01",
			 "A_F_M_KTown_02",
			 "A_F_O_KTown_01",
			 "A_M_M_MexCntry_01",
			 "A_M_M_MexLabor_01",
			 "A_M_Y_MexThug_01",
			 "G_M_M_MexBoss_01",
			 "G_M_M_MexBoss_02",
			 "U_M_Y_Mani",
			 "S_M_M_Mariachi_01",
			 "U_F_Y_SpyActress",			
			 "S_F_M_Maid_01",
			 "A_C_Boar",
			 "s_m_m_movalien_01",
			 "u_m_y_pogo_01",
			 "S_F_Y_Barter_01",							
	"S_M_M_MovSpace_01",
	"U_M_Y_Zombie_01",
	"s_m_y_blackops_01",
	"s_m_y_hwaycop_01",
	"a_c_boar",
	"a_c_cat_01",
	"prop_gas_tank_01a",
    "prop_gascyl_01a",
    "p_spinning_anus_s",
    "prop_cs_dildo_01",
    "prop_ld_toilet_01",                   
    "prop_ld_bomb_anim",                   
    "prop_ld_farm_couch01",                     
    "p_crahsed_heli_s",
    "prop_rock_4_big2",
    "prop_beachflag_le",                     
    "stt_prop_stunt_track_uturn",
    "stt_prop_stunt_track_turnice",
    "stt_prop_stunt_track_hill",                   
    "cs4_lod_01_slod3",
    "cs4_lod_01_slod1",          
    "dt1_11_slod1",	
    "prop_gas_tank_01a",
	"prop_gas_tank_01a",
    "prop_gascyl_01a",                     
    "p_spinning_anus_s",    
    "stt_prop_stunt_jump_l",
    "stt_prop_stunt_jump_lb",
    "stt_prop_stunt_jump_loop",
    "stt_prop_stunt_jump_m",
    "stt_prop_stunt_jump_mb",
    "stt_prop_stunt_jump_s",
    "stt_prop_stunt_jump_sb",
    "stt_prop_stunt_landing_zone_01",
    "stt_prop_stunt_ramp",
    "stt_prop_stunt_soccer_ball",
    "stt_prop_stunt_soccer_goal",
    "stt_prop_stunt_soccer_lball",
    "stt_prop_stunt_soccer_sball",
    "stt_prop_stunt_target",
    "stt_prop_stunt_target_small",
    "stt_prop_stunt_track_bumps",
    "stt_prop_stunt_track_cutout",
    "stt_prop_stunt_track_dwlink",
"stt_prop_stunt_track_dwlink_02",
"stt_prop_stunt_track_dwsh15",
"stt_prop_stunt_track_dwshort",
"stt_prop_stunt_track_dwslope15",
"stt_prop_stunt_track_dwslope30",
"stt_prop_stunt_track_dwslope45",
"stt_prop_stunt_track_dwturn",
"stt_prop_stunt_track_dwuturn",
"stt_prop_stunt_track_exshort",
"stt_prop_stunt_track_fork",
"stt_prop_stunt_track_funlng",
"stt_prop_stunt_track_funnel",
"stt_prop_stunt_track_hill",
"stt_prop_stunt_track_hill2",
"stt_prop_stunt_track_jump",
"stt_prop_stunt_track_link",
"stt_prop_stunt_track_otake",
"stt_prop_stunt_track_sh15",
"stt_prop_stunt_track_sh30",
"stt_prop_stunt_track_sh45",
"stt_prop_stunt_track_sh45_a",
"stt_prop_stunt_track_short",
"stt_prop_stunt_track_slope15",
"stt_prop_stunt_track_slope30",
"stt_prop_stunt_track_slope45",
"stt_prop_stunt_track_start	",
    "prop_cs_dildo_01",                    
    "prop_ld_toilet_01",                     
    "prop_ld_bomb_anim",                    
    "prop_ld_farm_couch01",                     
    "p_crahsed_heli_s",
    "prop_rock_4_big2",
    "prop_beachflag_le",
    "stt_prop_stunt_track_uturn",
    "stt_prop_stunt_track_turnice",
    "stt_prop_stunt_track_hill",
    "prop_gascyl_01a",
    "p_spinning_anus_s",
    "prop_cs_dildo_01",
    "prop_ld_toilet_01",
    "prop_ld_bomb_anim",
    "prop_ld_farm_couch01",
    "p_crahsed_heli_s",
    "prop_rock_4_big2",
    "prop_beachflag_le",
    "stt_prop_stunt_track_uturn",
    "stt_prop_stunt_track_turnice",
    "stt_prop_stunt_track_hill",	
    "gr_prop_damship_01a",
	"a_c_chickenhawk",
	"stt_prop_stunt_track_start",
	"stt_prop_stunt_track_otake",
	"stt_prop_stunt_track_sh30",
	"stt_prop_stunt_track_sh45",
	"stt_prop_stunt_track_sh45_A",
	"stt_prop_stunt_track_short",
	"stt_prop_stunt_track_slope15",
	"stt_prop_stunt_track_slope30",
	"stt_prop_stunt_track_slope45",
	"stt_prop_stunt_track_start",
	"stt_prop_stunt_track_dwslope45",
	"stt_prop_stunt_track_dwturn",
	"stt_prop_stunt_track_dwuturn",
	"stt_prop_stunt_track_exshort",
	"stt_prop_stunt_track_fork",
	"stt_prop_stunt_track_funing",
	"stt_prop_stunt_track_funnel",
	"stt_prop_stunt_track_hill",
	"stt_prop_stunt_track_hill2",
	"a_c_chimp",
	"s_f_y_hooker_03",
	"a_c_chop",
	"a_c_cormorant",
	"a_c_cow",
	"a_c_coyote",
	"v_ilev_found_cranebucket", --s_m_y_swat_01
	"s_m_y_swat_01",
	"p_cs_sub_hook_01_s",
	"a_c_crow",
	"a_c_dolphin",
	--------------- ANIMALES --------------	
	"a_c_crow",
	"a_c_dolphin",
	"a_c_boar",
	"a_c_cat_01",
	"a_c_chickenhawk",
	"a_c_chop",
	"a_c_cormorant",
	"a_c_cow",
	"a_c_coyote",
	"a_c_crow",
	"a_c_deer",
	"a_c_dolphin",
	"a_c_fish",
	"a_c_hen",
	"a_c_humpback",
	"a_c_husky",
	"a_c_killerwhale",
	"a_c_mtlion",
	"a_c_pig",
	"a_c_pigeon",
	"a_c_poodle",
	"a_c_pug",
	"a_c_rabbit_01",
	"a_c_rat",
	"a_c_retriever",
	"a_c_rhesus",
	"a_c_rottweiler",
	"a_c_seagull",
	"a_c_sharkhammer",
	"a_c_sharktiger",
	"a_c_shepherd",
	"a_c_stingray",
	"a_c_westy",
--------------- ANIMALES --------------	
	"a_c_fish"
}

-- Defaults to this ped model if an error happened
defaultpedmodel = "a_m_y_skater_01"

-- CODE --

Citizen.CreateThread(function()
	while true do
		Wait(0)

		playerPed = GetPlayerPed(-1)
		if playerPed then
			playerModel = GetEntityModel(playerPed)

			if not prevPlayerModel then
				if isPedBlacklisted(prevPlayerModel) then
					SetPlayerModel(PlayerId(), GetHashKey(defaultpedmodel))
				else
					prevPlayerModel = playerModel
				end
			else
				if isPedBlacklisted(playerModel) then
					SetPlayerModel(PlayerId(), prevPlayerModel)
					sendForbiddenMessage("Estan intentando spawnear NPCS, =Anticheat Tumberos= Limpiando NPCS EN 20 SEGUNDOS..!")
				end

				prevPlayerModel = playerModel
			end
		end
	end
end)

function isPedBlacklisted(model)
	for _, blacklistedPed in pairs(pedblacklist) do
		if model == GetHashKey(blacklistedPed) then
			return true
		end
	end

	return false
end